### ISSUE TITLE
Problem in cloning form the master table

### ISSUE THREAD

**Issue by uguryildirim** [DataTables/FixedColumns#50] opened 2016-01-21 13:13 UTC
Hello,

I found error in below this comment "add in the body elements, cloning form the master table".

If index is undefined, throw this error: undefined is not an object (evaluating 'f.s.dt.aoData[f.s.dt.oFeatures.bServerSide===false?f.s.dt.aiDisplay[f.s.dt._iDisplayStart+a]:a].anCells')

And i added this line and work perfectly. If is this ok for you can you fixed next release please? Thank for the great plugin.

Best regards

		$('>tbody>tr', that.dom.body).each( function (z) {
				var n = this.cloneNode(false);
				n.removeAttribute('id');
				var i = that.s.dt.oFeatures.bServerSide===false ?
					that.s.dt.aiDisplay[ that.s.dt._iDisplayStart+z ] : z;

				// If index undefined
				if(i === undefined){
					return;
				 }

				var aTds = that.s.dt.aoData[ i ].anCells || $(this).children('td, th');

				for ( iIndex=0 ; iIndex<aiColumns.length ; iIndex++ )
				{
					iColumn = aiColumns[iIndex];

					if ( aTds.length > 0 )
					{
						nClone = $( aTds[iColumn] ).clone(true, true)[0];
						n.appendChild( nClone );
					}
				}
				nBody.appendChild( n );
		} );

**Comment by DataTables** [comment] 2016-01-21 13:34
Can you link to a page showing the issue please.

**Comment by DataTables** [comment] 2016-02-02 16:38
I plan to do a release in the next few days. Can you give a test case showing the issue so I can address the issue in the code?

**Comment by uguryildirim** [comment] 2016-02-03 06:51
Hi, sorry for delay. I can't get link. Becuase project not public yet. If you can use FixedColumn and RowGrouping same time you can see that error. Thanks.

**Comment by DataTables** [comment] 2016-02-03 09:05
Thank you for the additional information - I wasn't aware that you were using a third party plug-in for DataTables (the row grouping).

Row grouping, and child rows, are not supported by FixedColumns at this time - see #18. Closing as a duplicate of #18.

**Closed by DataTables** 2016-02-03 09:05 UTC
