### ISSUE TITLE
Columns() and header() to prevent sort on header input select focus no longer works

### ISSUE THREAD

**Issue by Jrizzi1** [DataTables/FixedColumns#52] opened 2016-02-29 20:57 UTC
Found this today while attempting to upgrade, I have a javascript function that allows users to click on selects and inputs in the header, and the columns do not sort. Here is that code , which i gleaned from some previous datatables post:

```

$table.columns().eq( 0 ).each( function ( colIdx ) {

    $('input, select', $table.column(colIdx).header()).on('click', function(e) {
            e.stopPropagation();
        });
} );


```

here is the working example that uses 3.0.4 http://live.datatables.net/laxinabe/45/edit
here is the exact same code using 3.2.1 the code is ignored http://live.datatables.net/gizuqani/1/

last working version was  3.0.4, any version after that does not stop propagation

**Comment by DataTables** [comment] 2016-03-01 10:25
The problem is that:

    $('input, select', $table.column(colIdx).header())

doesn't give you to cloned elements so your event handler isn't applying to the fixed columns.

You can see the effect of setting the event handler directly onto the elements here: http://live.datatables.net/gizuqani/2/edit .

I've used a `setTimeout` there because we need to wait for the elements to be available before the event handler can be added.

I'm actually not sure what the best approach to resolve this is. The problem is knowing when the elements are recloned - there isn't a callback for that at the moment. My suggestion would actually be to move the search boxes into a separate row in the table header until I have a better solution for this!

Allan

p.s. In future, could you post support requests in the [forums](//datatables.net/forums) so there is a single, searchable location for them.

**Comment by Jrizzi1** [comment] 2016-03-01 15:17
no problem, do you want me to migrate it now?

**Comment by DataTables** [comment] 2016-03-01 15:25
We'll leave this one here - otherwise I'll get confused with it in two places :-)

**Comment by Jrizzi1** [comment] 2016-03-15 13:27
I am having difficulty implementing your suggested solution , the searches just are not firing, can you update the example with some code or point me in the right direction? i attempted moving the filtertes to the footer and putting a new row in the header, both would not fire the filter

**Comment by DataTables** [comment] 2016-03-16 08:59
Very happy to write a working example under the [DataTables support options](//datatables.net/support). However, as I say, you need to be _really_ careful about using input elements in the fixed elements. I would strongly recommend against it. The problem is that as soon as the table is redrawn, the elements are recloned and thus any existing input is removed which can be really horrible to deal with.

**Comment by Jrizzi1** [comment] 2016-03-17 15:13
Following the documentation example found here https://datatables.net/extensions/fixedcolumns/examples/styling/col_filter.html
it shows using input elements in the fixed elements

my previous code was following the previous example of this page which was updated feb. 2
https://github.com/DataTables/FixedColumns/commit/c0d9bca088a3b79e947454042981e35cb79d8be2

Is the recommendation that I shouldnt be doing this?

**Comment by AllanJard** [comment] 2023-10-30 15:39
Closing due to the v4 upgrade which significantly simplified FixedColumns through the use of `position sticky`. This removes the need for cloned elements and resolves a ton of issues, including this one.

**Closed by AllanJard** 2023-10-30 15:39 UTC
